version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: BlogDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      TZ: Asia/Seoul
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--lower-case-table-names=1'
    ]
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: [ "CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "blogdb" ]
      interval: 1s
      timeout: 3s
      retries: 30